from app.workspace_export.engine import WorkspaceExportEngine
from app.workspace_export.models import ExportFormat
from app.workspace_export.pipeline.markdown_repair import repair_markdown
from app.workspace_export.pipeline.orchestrator import prepare_export_document
from app.workspace_export.pipeline.unicode_normalizer import normalize_unicode


UNICODE_SAMPLE = """# Take\u2011Home Assignment

## Case\u00a0Study Round

Topics:
- In\u2011person interview
- Decision\u2011intelligence platform
- AI\u2011Platform integration

Generated by AI\u00a0Platform

| Stage | Focus |
| --- | --- |
| Round 1 | Problem\u2011solving |
"""

HTML_LEAK_SAMPLE = """# Report

Line one<br>Line two

<p>Paragraph with raw tag</p>

- [ ] Pending task
- [x] Completed task
"""


def test_unicode_normalization_replaces_special_hyphens():
    assert normalize_unicode("Take\u2011Home") == "Take-Home"
    assert normalize_unicode("Case\u00a0Study") == "Case Study"
    assert "\u2011" not in normalize_unicode("AI\u2011Platform")


def test_markdown_repair_strips_html_and_fixes_checkboxes():
    repaired = repair_markdown(HTML_LEAK_SAMPLE)
    assert "<br>" not in repaired.lower()
    assert "<p>" not in repaired.lower()
    assert "☐ Pending task" in repaired or "- ☐ Pending task" in repaired
    assert "✅ Completed task" in repaired or "- ✅ Completed task" in repaired


def test_prepare_export_document_validates_clean_pipeline():
    prepared = prepare_export_document(UNICODE_SAMPLE, title="Interview Plan")
    assert "\u2011" not in prepared.markdown
    assert "<br" not in prepared.html.lower()
    assert "Take-Home" in prepared.html or "Take-Home" in prepared.markdown


def test_pdf_export_has_no_unicode_hyphen_artifacts():
    engine = WorkspaceExportEngine()
    pdf, _, _ = engine.export(UNICODE_SAMPLE, ExportFormat.PDF, project_name="Demo")
    assert pdf[:4] == b"%PDF"
    # PDF binary should not contain the non-breaking hyphen byte sequence as text
    assert b"\xe2\x80\x91" not in pdf


def test_pdf_export_with_html_leak_repair():
    engine = WorkspaceExportEngine()
    pdf, _, _ = engine.export(HTML_LEAK_SAMPLE, ExportFormat.PDF, project_name="Demo")
    assert pdf[:4] == b"%PDF"


MALFORMED_TABLE_SAMPLE = """# Report

| Category | Details | Source |
| --- | --- | --- |
| **Core functionality** | - Implement authentication |
"""

SKIPPED_HEADING_SAMPLE = """# Title

### Subsection without H2

Body text.
"""

MATHCO_TABLE_SAMPLE = """# How to Prepare for the MathCo AI Analyst Campus Interview

Below is a step-by-step study and practice plan.

| Interview Stage | What the JD expects you to demonstrate | How to prepare (actionable steps) |
| --- | --- | --- |
| Aptitude Test - Online | General problem-solving, logical reasoning, quantitative ability. | 1. Solve 30-40 practice questions from standard campus aptitude packs.
1. Time yourself - aim for ≤ 30 min for a full test. |
| Communication Test - Online | Clear articulation, listening, concise written responses. | 1. Record yourself answering a 2-minute intro prompt.
1. Practice writing short business-style summaries. |

## Cultural Alignment

| Value | How to demonstrate it in interview |
| --- | --- |
| Stay curious | Share a moment when you identified a hidden data quality issue. |
| Take ownership | Describe a project where you led end-to-end delivery. |

| Day | Focus | Activity |
| --- | --- | --- |
| 1-2 | Aptitude | Complete one full online mock aptitude test. |
| 3-5 | Technical | Review data pipeline concepts. |
"""


def test_pdf_export_normalizes_malformed_tables():
    engine = WorkspaceExportEngine()
    pdf, _, _ = engine.export(MALFORMED_TABLE_SAMPLE, ExportFormat.PDF, project_name="Demo")
    assert pdf[:4] == b"%PDF"


def test_pdf_export_normalizes_skipped_heading_levels():
    engine = WorkspaceExportEngine()
    pdf, _, _ = engine.export(SKIPPED_HEADING_SAMPLE, ExportFormat.PDF, project_name="Demo")
    assert pdf[:4] == b"%PDF"


def test_pdf_export_converts_wide_tables_to_sections():
    from app.workspace_export.pipeline.debug_trace import extract_pdf_text

    engine = WorkspaceExportEngine()
    pdf, _, _ = engine.export(MATHCO_TABLE_SAMPLE, ExportFormat.PDF, project_name="MathCo")
    text = extract_pdf_text(pdf)

    assert pdf[:4] == b"%PDF"
    assert "Interview Stage" not in text or "Aptitude Test - Online" in text
    assert "| Communication Test" not in text
    assert "Cultural Alignment" in text
    assert "Stay curious" in text
