"""Build normalized, styled HTML from parsed markdown AST."""

from __future__ import annotations

import html

from app.workspace_export.layout.print_styles import PRINT_CSS
from app.workspace_export.markdown_parser import spans_to_markdown
from app.workspace_export.models import (
    BlockquoteBlock,
    BulletListBlock,
    CodeBlock,
    HeadingBlock,
    HorizontalRuleBlock,
    InlineSpan,
    ParagraphBlock,
    ParsedDocument,
    TableBlock,
)
from app.workspace_export.pipeline.html_sanitizer import sanitize_html
from app.workspace_export.pipeline.unicode_normalizer import normalize_unicode


def build_html_document(doc: ParsedDocument, *, title: str | None = None) -> str:
    doc_title = normalize_unicode(title or doc.title or "AI Response")
    parts = [
        "<!DOCTYPE html>",
        "<html><head><meta charset='utf-8'>",
        f"<style>{PRINT_CSS}</style>",
        "</head><body>",
        f"<h1 class='doc-title'>{_esc(doc_title)}</h1>",
    ]

    for block in doc.blocks:
        parts.append(_block_to_html(block))

    parts.append("<p class='doc-footer'>Generated using AI Assistant</p>")
    parts.append("</body></html>")
    return sanitize_html("\n".join(parts))


def build_metadata_html(
    *,
    title: str,
    generated_label: str,
    project_name: str | None,
    platform_name: str,
) -> str:
    rows = [f"<dt>Date:</dt><dd>{_esc(generated_label)}</dd>"]
    if project_name:
        rows.append(f"<dt>Project:</dt><dd>{_esc(project_name)}</dd>")
    rows.append(f"<dt>Generated By:</dt><dd>{_esc(platform_name)}</dd>")
    return f"<dl class='doc-meta'>{''.join(rows)}</dl>"


def _block_to_html(block) -> str:
    if isinstance(block, HeadingBlock):
        level = min(max(block.level, 1), 4)
        return f"<h{level}>{_inline_html(block.spans)}</h{level}>"
    if isinstance(block, ParagraphBlock):
        return f"<p>{_inline_html(block.spans)}</p>"
    if isinstance(block, BulletListBlock):
        tag = "ol" if block.ordered else "ul"
        items = []
        for item in block.items:
            prefix = ""
            if item.checked is True:
                prefix = "☑ "
            elif item.checked is False:
                prefix = "☐ "
            items.append(f"<li>{prefix}{_inline_html(item.spans)}</li>")
        return f"<{tag}>{''.join(items)}</{tag}>"
    if isinstance(block, TableBlock):
        parts = []
        if block.title:
            parts.append(f"<h3>{_esc(block.title)}</h3>")
        parts.append("<table><thead><tr>")
        parts.extend(f"<th>{_inline_html(h)}</th>" for h in block.headers)
        parts.append("</tr></thead><tbody>")
        for row in block.rows:
            parts.append("<tr>")
            parts.extend(f"<td>{_inline_html(cell)}</td>" for cell in row)
            parts.append("</tr>")
        parts.append("</tbody></table>")
        return "".join(parts)
    if isinstance(block, CodeBlock):
        return f"<pre><code>{_esc(block.code)}</code></pre>"
    if isinstance(block, HorizontalRuleBlock):
        return "<hr />"
    if isinstance(block, BlockquoteBlock):
        inner = "".join(_block_to_html(n) for n in block.blocks)
        return f"<blockquote>{inner}</blockquote>"
    return ""


def _inline_html(spans: list[InlineSpan]) -> str:
    parts: list[str] = []
    for span in spans:
        text = _esc(normalize_unicode(span.text))
        if span.code:
            text = f"<code>{text}</code>"
        if span.bold:
            text = f"<strong>{text}</strong>"
        if span.italic:
            text = f"<em>{text}</em>"
        if span.link:
            href = _esc(span.link)
            text = f'<a href="{href}">{text}</a>'
        parts.append(text)
    return "".join(parts) or ""


def _esc(value: str) -> str:
    return html.escape(value, quote=True)
