from __future__ import annotations

from io import BytesIO

from docx import Document
from docx.shared import Inches, Pt, RGBColor

from app.workspace_export.markdown_parser import parse_markdown, spans_to_markdown
from app.workspace_export.models import (
    BlockquoteBlock,
    BulletListBlock,
    CodeBlock,
    ExportMetadata,
    HeadingBlock,
    HorizontalRuleBlock,
    InlineSpan,
    ParagraphBlock,
    TableBlock,
)


def render_docx(content: str, metadata: ExportMetadata) -> bytes:
    doc = parse_markdown(content)
    document = Document()
    _set_default_styles(document)
    _add_metadata(document, metadata)
    for block in doc.blocks:
        _add_block(document, block)
    _add_footer(document)
    buffer = BytesIO()
    document.save(buffer)
    return buffer.getvalue()


def _set_default_styles(document: Document) -> None:
    section = document.sections[0]
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)
    normal = document.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)


def _add_metadata(document: Document, metadata: ExportMetadata) -> None:
    title = document.add_heading(metadata.title, level=0)
    title.runs[0].font.color.rgb = RGBColor(0x33, 0x33, 0x33)
    meta = document.add_paragraph()
    meta.add_run(f"Generated: {metadata.generated_at.strftime('%B %d, %Y at %I:%M %p')}\n").italic = True
    if metadata.project_name:
        meta.add_run(f"Project: {metadata.project_name}\n").italic = True
    meta.add_run(f"Generated by {metadata.platform_name}").italic = True
    document.add_paragraph("")


def _add_footer(document: Document) -> None:
    document.add_paragraph("")
    footer = document.add_paragraph("Generated using AI Assistant")
    footer.runs[0].italic = True
    footer.runs[0].font.size = Pt(9)
    footer.runs[0].font.color.rgb = RGBColor(0x66, 0x66, 0x66)


def _add_block(document: Document, block) -> None:
    if isinstance(block, HeadingBlock):
        document.add_heading(spans_to_markdown(block.spans), level=min(block.level, 4))
    elif isinstance(block, ParagraphBlock):
        _add_rich_paragraph(document, block.spans)
    elif isinstance(block, BulletListBlock):
        style = "List Number" if block.ordered else "List Bullet"
        for item in block.items:
            text = spans_to_markdown(item.spans)
            if item.checked is True:
                text = f"☑ {text}"
            elif item.checked is False:
                text = f"☐ {text}"
            document.add_paragraph(text, style=style)
    elif isinstance(block, TableBlock):
        if block.title:
            document.add_heading(block.title, level=3)
        cols = max(len(block.headers), max((len(r) for r in block.rows), default=0))
        table = document.add_table(rows=1 + len(block.rows), cols=cols)
        table.style = "Table Grid"
        for col_idx, header in enumerate(block.headers):
            cell = table.rows[0].cells[col_idx]
            cell.text = spans_to_markdown(header)
            for run in cell.paragraphs[0].runs:
                run.bold = True
        for row_idx, row in enumerate(block.rows, start=1):
            for col_idx, cell_spans in enumerate(row):
                table.rows[row_idx].cells[col_idx].text = spans_to_markdown(cell_spans)
        document.add_paragraph("")
    elif isinstance(block, CodeBlock):
        para = document.add_paragraph()
        run = para.add_run(block.code)
        run.font.name = "Consolas"
        run.font.size = Pt(9)
        para.paragraph_format.left_indent = Inches(0.25)
    elif isinstance(block, HorizontalRuleBlock):
        document.add_paragraph("_" * 50)
    elif isinstance(block, BlockquoteBlock):
        for nested in block.blocks:
            _add_block(document, nested)
            for para in document.paragraphs[-1:]:
                para.paragraph_format.left_indent = Inches(0.35)


def _add_rich_paragraph(document: Document, spans: list[InlineSpan]):
    para = document.add_paragraph()
    for span in spans:
        run = para.add_run(span.text)
        run.bold = span.bold
        run.italic = span.italic
        if span.code:
            run.font.name = "Consolas"
            run.font.size = Pt(10)
        if span.link:
            run.font.color.rgb = RGBColor(0x05, 0x63, 0xC1)
            run.underline = True
    return para
