from __future__ import annotations

from app.workspace_export.markdown_parser import document_to_markdown, parse_markdown
from app.workspace_export.models import ExportMetadata, ParsedDocument


def render_markdown(content: str, metadata: ExportMetadata) -> str:
    doc = parse_markdown(content)
    body = document_to_markdown(doc)
    header = _metadata_markdown(metadata)
    footer = "\n\n---\n\n*Generated using AI Assistant*"
    return f"{header}\n\n{body}{footer}\n"


def _metadata_markdown(metadata: ExportMetadata) -> str:
    lines = [f"# {metadata.title}", ""]
    lines.append(f"**Generated:** {metadata.generated_at.strftime('%B %d, %Y at %I:%M %p')}")
    if metadata.project_name:
        lines.append(f"**Project:** {metadata.project_name}")
    lines.append(f"**Generated by:** {metadata.platform_name}")
    return "\n".join(lines)
