from __future__ import annotations

from app.workspace_export.models import ExportMetadata, InlineSpan, ParsedDocument
from app.workspace_export.markdown_parser import spans_to_markdown


def render_text(doc: ParsedDocument, metadata: ExportMetadata) -> str:
    lines: list[str] = []
    lines.extend(_metadata_lines(metadata))
    lines.append("")

    for block in doc.blocks:
        lines.extend(_block_to_text(block, indent=0))
        lines.append("")

    lines.extend(["", "—" * 40, "Generated using AI Assistant"])
    return "\n".join(line for line in lines if line is not None).strip() + "\n"


def _metadata_lines(metadata: ExportMetadata) -> list[str]:
    lines = [metadata.title, "=" * len(metadata.title)]
    lines.append(f"Generated: {metadata.generated_at.strftime('%B %d, %Y at %I:%M %p')}")
    if metadata.project_name:
        lines.append(f"Project: {metadata.project_name}")
    lines.append(f"Generated by {metadata.platform_name}")
    return lines


def _block_to_text(block, indent: int = 0) -> list[str]:
    prefix = "  " * indent
    from app.workspace_export.models import (
        BlockquoteBlock,
        BulletListBlock,
        CodeBlock,
        HeadingBlock,
        HorizontalRuleBlock,
        ParagraphBlock,
        TableBlock,
    )

    if isinstance(block, HeadingBlock):
        marker = "#" * block.level
        return [f"{prefix}{marker} {_plain(block.spans)}"]
    if isinstance(block, ParagraphBlock):
        return [f"{prefix}{_plain(block.spans)}"]
    if isinstance(block, BulletListBlock):
        out: list[str] = []
        for idx, item in enumerate(block.items, start=1):
            bullet = f"{idx}." if block.ordered else "-"
            if item.checked is True:
                bullet = "[x]"
            elif item.checked is False:
                bullet = "[ ]"
            out.append(f"{prefix}{bullet} {_plain(item.spans)}")
        return out
    if isinstance(block, TableBlock):
        out = []
        if block.title:
            out.append(f"{prefix}{block.title}")
        header = " | ".join(_plain(h) for h in block.headers)
        out.append(f"{prefix}{header}")
        out.append(f"{prefix}{'-' * max(len(header), 3)}")
        for row in block.rows:
            out.append(f"{prefix}{' | '.join(_plain(cell) for cell in row)}")
        return out
    if isinstance(block, CodeBlock):
        return [f"{prefix}```{block.language}", *[f"{prefix}{line}" for line in block.code.splitlines()], f"{prefix}```"]
    if isinstance(block, HorizontalRuleBlock):
        return [f"{prefix}{'-' * 40}"]
    if isinstance(block, BlockquoteBlock):
        out = []
        for nested in block.blocks:
            for line in _block_to_text(nested, indent + 1):
                out.append(f"{prefix}> {line.strip()}")
        return out
    return []


def _plain(spans: list[InlineSpan]) -> str:
    return spans_to_markdown(spans)
