from __future__ import annotations

from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter

from app.workspace_export.markdown_parser import parse_markdown, spans_to_markdown
from app.workspace_export.models import ExportMetadata, TableBlock


def render_xlsx(content: str, metadata: ExportMetadata) -> bytes:
    doc = parse_markdown(content)
    tables = [block for block in doc.blocks if isinstance(block, TableBlock)]
    if not tables:
        raise ValueError("No tabular content available for Excel export")

    workbook = Workbook()
    workbook.remove(workbook.active)

    for idx, table in enumerate(tables, start=1):
        title = table.title or f"Table_{idx}"
        sheet_name = _safe_sheet_name(title, idx)
        sheet = workbook.create_sheet(title=sheet_name)
        _write_table(sheet, table)

    meta_sheet = workbook.create_sheet(title="Document_Info", index=0)
    meta_sheet["A1"] = metadata.title
    meta_sheet["A1"].font = Font(bold=True, size=14)
    meta_sheet["A2"] = f"Generated: {metadata.generated_at.strftime('%Y-%m-%d %H:%M')}"
    if metadata.project_name:
        meta_sheet["A3"] = f"Project: {metadata.project_name}"
    meta_sheet["A4"] = f"Generated by {metadata.platform_name}"
    meta_sheet["A5"] = "Generated using AI Assistant"
    meta_sheet.column_dimensions["A"].width = 48

    buffer = BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


def _write_table(sheet, table: TableBlock) -> None:
    if table.title:
        sheet["A1"] = table.title
        sheet["A1"].font = Font(bold=True, size=12)
        start_row = 3
    else:
        start_row = 1

    header_fill = PatternFill("solid", fgColor="E8EEF7")
    header_font = Font(bold=True)

    for col_idx, header in enumerate(table.headers, start=1):
        cell = sheet.cell(row=start_row, column=col_idx, value=spans_to_markdown(header))
        cell.font = header_font
        cell.fill = header_fill

    for row_idx, row in enumerate(table.rows, start=start_row + 1):
        for col_idx, cell_spans in enumerate(row, start=1):
            sheet.cell(row=row_idx, column=col_idx, value=spans_to_markdown(cell_spans))

    for col_idx in range(1, len(table.headers) + 1):
        letter = get_column_letter(col_idx)
        max_len = 12
        for row in sheet.iter_rows(min_col=col_idx, max_col=col_idx):
            for cell in row:
                if cell.value:
                    max_len = max(max_len, min(len(str(cell.value)) + 2, 60))
        sheet.column_dimensions[letter].width = max_len


def _safe_sheet_name(name: str, index: int) -> str:
    cleaned = "".join(ch if ch.isalnum() or ch in (" ", "_", "-") else "_" for ch in name)
    cleaned = cleaned.strip()[:28] or f"Table_{index}"
    return cleaned
